### ISSUE TITLE
Provide a way to set custom accent colour

### ISSUE THREAD

**Issue by ConfusedVorlon** [chkn/MaterialUI#2]
strangely - the accentColor modifier is not available in MacOS

this means material is blue only...
https://developer.apple.com/documentation/swiftui/view/3280159-accentcolor

**Comment by chkn** [comment]
I think that for Mac the accent color is set in System Preferences.

From the link you mentioned, it does look like the API is being added for macOS 11, with this caveat:

> On macOS, customization of the accent color is only applied if the “Multicolor” accent color is selected in System Preferences.

**Comment by ConfusedVorlon** [comment]
I hadn't realised it was in system prefs. Either way - it's annoying not to be able to control it in the design.
Any chance of an alternative method for setting it that would be useable on MacOS?

**Comment by chkn** [comment]
Yeah I think that could be good. One option might be to add a [custom environment key](https://medium.com/@SergDort/custom-environment-keys-in-swiftui-49f54a13d140), e.g. `materialAccentColor`, that defaults to `Color.accentColor`

**Comment by ConfusedVorlon** [comment]
I'll give it a go
